# Common Features
USER_ID_FIELD: user_id
ITEM_ID_FIELD: aisle_id

CATE_ID1: cate_id
CATE_ID2: top_k
COMMON_U: weight


#RATING_FIELD: rating
TIME_FIELD: timestamp
# Selectively Loading
load_meta_cols: [itemID, description, title, category]

TEXT_ID_FIELD: description
filter_out_cod_start_users: True

# file for generate item_item.csv & testing
inter_file_name: 'item_item.csv' 
# file to train item-item interract
item_item_inter: 'item_item.csv' 
text_file_name: 'meta-games-indexed.csv'
img_dir_name: 'img'

# name of frozen features
u_i_interaction_file: 'interaction.csv'
vision_feature_file: 'img_feat.npy'
text_feature_file: 'text_feat.npy'
user_graph_dict_file: 'user_graph_dict.npy'
item_graph_dict_file: 'item_graph_dict.npy'
user_item_dict_file: 'user_item_dict.npy'

max_img_size: 256

field_separator: "\t"
